[tool.poetry]
name = "pythonanywhere-core"
version = "0.1.3"
description = "API wrapper for programmatic management of PythonAnywhere services."
authors = ["PythonAnywhere <developers@pythonanywhere.com>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.7",
]
keywords = ["pythonanywhere", "api", "cloud", "web hosting"]

[tool.poetry.dependencies]
python = "^3.7"
python-dateutil = "^2.8.2"
requests = "^2.30.0"
snakesay = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
responses = "^0.22.0"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
